save current draft of analyses

diff --git a/TabulaSenis/raw_data_processing/SS2_Snakemake/MONTH3/Snakefile b/TabulaSenis/raw_data_processing/SS2_Snakemake/MONTH3/Snakefile
--- a/TabulaSenis/raw_data_processing/SS2_Snakemake/MONTH3/Snakefile
+++ b/TabulaSenis/raw_data_processing/SS2_Snakemake/MONTH3/Snakefile
@@ -16,8 +16,10 @@ sample_bam_map = get_sample_ids()
 
 rule all:
     input:
-        expand("{results_dir}/{sample}/junctions_with_barcodes.bed", 
-               results_dir=config["results_dir"], sample=sample_bam_map.keys())
+        expand("{results_dir}/{sample}/junctions_with_barcodes.bed",
+               results_dir=config["results_dir"], sample=list(sample_bam_map.keys())),
+        expand("{results_dir}/{sample}_splicing_summary.tsv",
+               results_dir=config["results_dir"], sample=list(sample_bam_map.keys()))
 
 # Rule to add CB tag to BAM files
 rule add_cb_tag:
@@ -27,11 +29,18 @@ rule add_cb_tag:
         bam_CB = config["results_dir"] + "/{sample}/CB.bam"
     shell:
         """
-        echo "Adding CB tag to BAM file: {input.bam}"
-        samtools view -h {input.bam} | awk -v cb={wildcards.sample} 'BEGIN {{OFS="\t"}} {{$NF = $NF"\tCB:Z:"cb; print}}' | samtools view -bS - > {output.bam_CB}
+        echo "Processing sample: {wildcards.sample}"
+        echo "Expected BAM path: {input.bam}"
+
+        if [[ ! -f "{input.bam}" ]]; then
+            echo "ERROR: BAM file {input.bam} not found!"
+            exit 1
+        fi
+
+        samtools view -h {input.bam} | awk -v cb="{wildcards.sample}" 'BEGIN {{OFS="\\t"}} {{if ($1 ~ /^@/) print; else print $0 "\\tCB:Z:" cb;}}' | samtools view -b - > {output.bam_CB}
         """
 
-# rule index the bam file
+# Rule to index the BAM file
 rule index_bam:
     input:
         bam = rules.add_cb_tag.output.bam_CB
@@ -43,31 +52,7 @@ rule index_bam:
         samtools index {input.bam}
         """
 
-###############################################################################
-# Rule: MarkDuplicates with Picard 
-# havent fix this yet
-###############################################################################
-rule markduplicates:
-    input:
-        bam = rules.add_cb_tag.output.bam_CB
-        bai = rules.index_bam.output.bai
-    output:
-        bam_dedup = config["results_dir"] + "/{sample}/CB_dedup.bam",
-        metrics   = config["results_dir"] + "/{sample}/dedup_metrics.txt"
-    shell:
-        """
-        echo "Marking duplicates with Picard for: {input.bam}"
-        java -jar {params.picard_jar} MarkDuplicates \
-            I={input.bam} \
-            O={output.bam_dedup} \
-            M={output.metrics} \
-            CREATE_INDEX=true \
-            VALIDATION_STRINGENCY=LENIENT \
-            REMOVE_DUPLICATES=false
-        echo "Done marking duplicates"
-        """
-
-# Rule to extract junctions with barcodes
+# Rule to extract junctions with barcodes (without deleting the BAM file)
 rule extract_junctions:
     input:
         bam = rules.add_cb_tag.output.bam_CB,
@@ -82,40 +67,32 @@ rule extract_junctions:
         """
         echo "Extracting junctions with barcodes from BAM file: {input.bam}"
         {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} -o {output.juncs} -s XS -b {output.barcodes}
+
         # Combine junctions and barcodes
         paste --delimiters='\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}
-        # Delete input bam file no longer needed 
-        rm {input.bam}
-        rm {input.bai}
+
         echo "Done extracting junctions with barcodes"
         """
 
-###############################################################################
-# Rule: Extract junctions (using the deduplicated BAM)
-###############################################################################
-rule extract_junctions:
+# Rule to summarize splicing
+rule summarize_splicing:
     input:
-        bam = rules.markduplicates.output.bam_dedup,
-        # the MarkDuplicates step creates .bai automatically if CREATE_INDEX=true,
-        # but if you prefer to specify:
-        # bai = rules.markduplicates.output.bam_dedup.replace(".bam", ".bai")
+        bam = rules.add_cb_tag.output.bam_CB,
+        juncs = config["results_dir"] + "/{sample}/junctions.bed"
     output:
-        juncs         = config["results_dir"] + "/{sample}/junctions.bed",
-        barcodes      = config["results_dir"] + "/{sample}/barcodes.txt",
-        juncswbarcodes = config["results_dir"] + "/{sample}/junctions_with_barcodes.bed"
-    params:
-        regtools_path = config["regtools_path"]
+        summary = config["results_dir"] + "/{sample}_splicing_summary.tsv"
     shell:
         """
-        echo "Extracting junctions with barcodes from BAM file: {input.bam}"
-        {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} \
-            -o {output.juncs} -s XS -b {output.barcodes}
-        # Combine junctions and barcodes
-        paste --delimiters='\\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}
-        
-        # Remove the deduplicated BAM and index if you no longer need them
-        # rm {input.bam}
-        # rm {input.bam}.bai
-        
-        echo "Done extracting junctions with barcodes"
+        echo -e "Sample\tTotal_Reads\tSpliced_Reads\tUnspliced_Reads" > {output.summary}
+
+        sample=$(basename {input.bam} | cut -d'.' -f1)
+        total_reads=$(samtools view -c -F 4 {input.bam})
+
+        # Ensure the file has at least five columns before extracting spliced reads
+        spliced_reads=$(awk '{{if (NF >= 5) sum += $5}} END {{print (sum == "" ? 0 : sum)}}' "{input.juncs}")
+
+        unspliced_reads=$((total_reads - spliced_reads))
+
+        echo -e "$sample\t$total_reads\t$spliced_reads\t$unspliced_reads" >> {output.summary}
+        echo "Splicing summary written to {output.summary}"
         """
